#!/usr/bin/env python3
"""Replace prod_022–prod_031 with 10 halal noodle SKUs (keeps 36-product test contract)."""

from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "data" / "catalog.json"

NOODLES = [
    {
        "product_id": "prod_022",
        "title": "Halal Mi Goreng Classic 5-pack",
        "description": "Budget-friendly fried noodles, MUI halal certified. Best value in Jakarta.",
        "seller_id": "seller_001",
        "price": 18500,
        "currency": "IDR",
        "country": "Indonesia",
        "city": "Jakarta",
        "halal_status": "certified",
        "halal_certifier": "LPPOM MUI",
        "halal_certificate_id": "HALAL-ID-022",
        "cod_available": True,
        "cod_max_amount": 500000,
        "cod_supported_cities": ["Jakarta"],
        "bnpl_available": False,
        "discount_pct": 15,
        "rating": 4.9,
        "sold_count": 52000,
    },
    {
        "product_id": "prod_023",
        "title": "Halal Chicken Cup Noodles 4-pack",
        "description": "Single-serve cups, quick lunch, halal certified.",
        "seller_id": "seller_001",
        "price": 12000,
        "currency": "IDR",
        "country": "Indonesia",
        "city": "Jakarta",
        "halal_status": "certified",
        "halal_certifier": "LPPOM MUI",
        "halal_certificate_id": "HALAL-ID-023",
        "cod_available": True,
        "cod_max_amount": 500000,
        "cod_supported_cities": ["Jakarta"],
        "bnpl_available": False,
        "discount_pct": 10,
        "rating": 4.7,
        "sold_count": 31000,
    },
    {
        "product_id": "prod_024",
        "title": "Budget Halal Instant Noodles 3-pack",
        "description": "Affordable pantry pack from Manila. Card payment only.",
        "seller_id": "seller_004",
        "price": 89,
        "currency": "PHP",
        "country": "Philippines",
        "city": "Manila",
        "halal_status": "certified",
        "halal_certifier": "Halal PH Stub",
        "halal_certificate_id": "HALAL-PH-024",
        "cod_available": False,
        "cod_max_amount": 0,
        "cod_supported_cities": [],
        "bnpl_available": False,
        "discount_pct": 20,
        "rating": 4.4,
        "sold_count": 8900,
    },
    {
        "product_id": "prod_025",
        "title": "Spicy Halal Tom Yum Noodles",
        "description": "Thai-style spicy bowl noodles, halal status pending verification.",
        "seller_id": "seller_005",
        "price": 45,
        "currency": "THB",
        "country": "Thailand",
        "city": "Bangkok",
        "halal_status": "unknown",
        "halal_certifier": None,
        "halal_certificate_id": None,
        "cod_available": True,
        "cod_max_amount": 1500,
        "cod_supported_cities": ["Bangkok"],
        "bnpl_available": True,
        "discount_pct": 5,
        "rating": 4.5,
        "sold_count": 12400,
    },
    {
        "product_id": "prod_026",
        "title": "Premium Halal Udon Noodles 6-pack",
        "description": "Thick wheat udon, restaurant-style quality, halal certified.",
        "seller_id": "seller_005",
        "price": 120,
        "currency": "THB",
        "country": "Thailand",
        "city": "Bangkok",
        "halal_status": "certified",
        "halal_certifier": "CICOT Stub",
        "halal_certificate_id": "HALAL-TH-026",
        "cod_available": True,
        "cod_max_amount": 1500,
        "cod_supported_cities": ["Bangkok"],
        "bnpl_available": True,
        "discount_pct": 0,
        "rating": 4.8,
        "sold_count": 6700,
    },
    {
        "product_id": "prod_027",
        "title": "Singapore Halal Laksa Noodles 2-pack",
        "description": "Coconut curry laksa paste with noodles. Seller does not offer COD.",
        "seller_id": "seller_002",
        "price": 3.5,
        "currency": "SGD",
        "country": "Singapore",
        "city": "Singapore",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-027",
        "cod_available": False,
        "cod_max_amount": 0,
        "cod_supported_cities": [],
        "bnpl_available": True,
        "discount_pct": 12,
        "rating": 4.6,
        "sold_count": 15800,
    },
    {
        "product_id": "prod_028",
        "title": "KL Halal Curry Mee Instant Noodles",
        "description": "Malaysian curry noodle soup, JAKIM halal certified.",
        "seller_id": "seller_003",
        "price": 4.9,
        "currency": "MYR",
        "country": "Malaysia",
        "city": "Kuala Lumpur",
        "halal_status": "certified",
        "halal_certifier": "JAKIM",
        "halal_certificate_id": "HALAL-MY-028",
        "cod_available": True,
        "cod_max_amount": 300,
        "cod_supported_cities": ["Kuala Lumpur"],
        "bnpl_available": True,
        "discount_pct": 8,
        "rating": 4.7,
        "sold_count": 9400,
    },
    {
        "product_id": "prod_029",
        "title": "Family Halal Noodle Bundle 12-pack",
        "description": "Bulk pack for households, lowest per-serving price in IDR.",
        "seller_id": "seller_001",
        "price": 89000,
        "currency": "IDR",
        "country": "Indonesia",
        "city": "Jakarta",
        "halal_status": "certified",
        "halal_certifier": "LPPOM MUI",
        "halal_certificate_id": "HALAL-ID-029",
        "cod_available": True,
        "cod_max_amount": 500000,
        "cod_supported_cities": ["Jakarta"],
        "bnpl_available": True,
        "discount_pct": 25,
        "rating": 4.9,
        "sold_count": 22000,
    },
    {
        "product_id": "prod_030",
        "title": "Halal ABC Noodle Soup Sachets 10x",
        "description": "Clear soup noodles popular in Thailand, halal unknown.",
        "seller_id": "seller_005",
        "price": 32,
        "currency": "THB",
        "country": "Thailand",
        "city": "Bangkok",
        "halal_status": "unknown",
        "halal_certifier": None,
        "halal_certificate_id": None,
        "cod_available": True,
        "cod_max_amount": 1500,
        "cod_supported_cities": ["Bangkok"],
        "bnpl_available": False,
        "discount_pct": 0,
        "rating": 4.3,
        "sold_count": 4500,
    },
    {
        "product_id": "prod_031",
        "title": "Saigon Halal Pho Instant Noodles",
        "description": "Vietnamese pho-style instant noodles for Ho Chi Minh City delivery.",
        "seller_id": "seller_005",
        "price": 185000,
        "currency": "VND",
        "country": "Vietnam",
        "city": "Ho Chi Minh City",
        "halal_status": "unknown",
        "halal_certifier": None,
        "halal_certificate_id": None,
        "cod_available": True,
        "cod_max_amount": 1000000,
        "cod_supported_cities": ["Ho Chi Minh City"],
        "bnpl_available": False,
        "discount_pct": 18,
        "rating": 4.5,
        "sold_count": 11200,
    },
]


def template(row: dict) -> dict:
    pid = row["product_id"]
    num = pid.replace("prod_", "")
    return {
        "product_id": pid,
        "variant_id": f"variant_{num}",
        "seller_id": row["seller_id"],
        "title": row["title"],
        "description": row["description"],
        "category": "groceries",
        "price": row["price"],
        "currency": row["currency"],
        "availability": "in_stock",
        "country": row["country"],
        "city": row["city"],
        "delivery_starts_at": "2026-06-07T09:00:00+07:00",
        "delivery_ends_at": "2026-06-10T18:00:00+07:00",
        "halal_status": row["halal_status"],
        "halal_certifier": row.get("halal_certifier"),
        "halal_certificate_id": row.get("halal_certificate_id"),
        "halal_expires_at": "2027-12-31" if row["halal_status"] == "certified" else None,
        "bpom_status": "not_required",
        "bpom_registration_number": None,
        "bpom_expires_at": None,
        "cod_available": row["cod_available"],
        "cod_max_amount": row["cod_max_amount"],
        "cod_supported_cities": row["cod_supported_cities"],
        "cod_requires_buyer_confirmation": row["cod_available"],
        "bnpl_available": row["bnpl_available"],
        "bnpl_provider": "SPayLater" if row["bnpl_available"] else None,
        "return_window_days": 3,
        "image_url": f"/images/products/{pid}.jpg",
        "rating": row["rating"],
        "sold_count": row["sold_count"],
        "discount_pct": row["discount_pct"],
    }


def main() -> None:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    by_id = {row["product_id"]: row for row in catalog}
    for spec in NOODLES:
        by_id[spec["product_id"]] = template(spec)
    # Keep prod_006 as extra noodle option for search
    if "prod_006" in by_id:
        p6 = by_id["prod_006"]
        p6["title"] = "Halal Instant Noodle Pack 5x"
        p6["description"] = "Quick-cook halal instant noodles, pantry staple for Jakarta households."
        p6["image_url"] = "/images/products/prod_006.jpg"
    updated = [by_id[row["product_id"]] for row in catalog]
    CATALOG.write_text(json.dumps(updated, indent=2) + "\n", encoding="utf-8")
    print(f"Updated {len(NOODLES)} noodle SKUs in catalog ({len(updated)} total)")


if __name__ == "__main__":
    main()
