#!/usr/bin/env python3
"""Update noodle SKUs for Singapore $10 halal demo while keeping 36 total products."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "data" / "catalog.json"

SG_BASE = {
    "category": "groceries",
    "currency": "SGD",
    "country": "Singapore",
    "city": "Singapore",
    "delivery_starts_at": "2026-06-07T09:00:00+08:00",
    "delivery_ends_at": "2026-06-10T20:00:00+08:00",
    "bpom_status": "not_required",
    "bpom_registration_number": None,
    "bpom_expires_at": None,
    "cod_available": True,
    "cod_max_amount": 80,
    "cod_supported_cities": ["Singapore"],
    "cod_requires_buyer_confirmation": True,
    "bnpl_available": True,
    "bnpl_provider": "SPayLater",
    "return_window_days": 3,
    "seller_id": "seller_003",
}

NOODLES = {
    "prod_006": {
        "title": "Spicy Curry Noodles Pack",
        "description": "Halal-certified curry instant noodles. Pantry staple for Singapore households.",
        "price": 6.9,
        "availability": "in_stock",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-006",
        "halal_expires_at": "2028-06-30",
        "rating": 4.8,
        "review_count": 1200,
        "sold_count": 8000,
        "discount_pct": 10,
        "image_url": "/images/products/prod_006.jpg",
    },
    "prod_022": {
        "title": "Budget Halal Instant Noodles 3-pack",
        "description": "Value pantry pack with MUIS halal certification.",
        "price": 5.5,
        "availability": "in_stock",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-022",
        "halal_expires_at": "2028-03-15",
        "rating": 4.5,
        "review_count": 800,
        "sold_count": 5200,
        "discount_pct": 15,
        "image_url": "/images/products/prod_022.jpg",
    },
    "prod_023": {
        "title": "Halal Chicken Cup Noodles 4-pack",
        "description": "Single-serve cups, quick lunch, MUIS halal certified.",
        "price": 7.4,
        "availability": "in_stock",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-023",
        "halal_expires_at": "2028-01-20",
        "rating": 4.7,
        "review_count": 640,
        "sold_count": 4100,
        "discount_pct": 8,
        "image_url": "/images/products/prod_023.jpg",
    },
    "prod_024": {
        "title": "Popular Instant Noodles 5-pack",
        "description": "Seller claims Halal but certificate proof is missing. Best seller by volume.",
        "price": 4.9,
        "availability": "in_stock",
        "halal_status": "unknown",
        "halal_certifier": None,
        "halal_certificate_id": None,
        "halal_expires_at": None,
        "rating": 4.9,
        "review_count": 3000,
        "sold_count": 20000,
        "discount_pct": 20,
        "image_url": "/images/products/prod_024.jpg",
    },
    "prod_025": {
        "title": "Spicy Halal Tom Yum Noodles",
        "description": "Thai-style spicy bowl. Halal claim pending verification.",
        "price": 6.2,
        "availability": "in_stock",
        "halal_status": "unknown",
        "halal_certifier": None,
        "halal_certificate_id": None,
        "halal_expires_at": None,
        "rating": 4.6,
        "review_count": 420,
        "sold_count": 9800,
        "discount_pct": 5,
        "image_url": "/images/products/prod_025.jpg",
    },
    "prod_026": {
        "title": "Premium Halal Udon Noodles 6-pack",
        "description": "Restaurant-style thick udon, MUIS halal certified.",
        "price": 11.2,
        "availability": "in_stock",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-026",
        "halal_expires_at": "2028-09-01",
        "rating": 4.8,
        "review_count": 900,
        "sold_count": 4000,
        "discount_pct": 0,
        "image_url": "/images/products/prod_026.jpg",
    },
    "prod_027": {
        "title": "Singapore Halal Laksa Noodles 2-pack",
        "description": "Coconut curry laksa paste with noodles. MUIS certified.",
        "price": 5.8,
        "availability": "in_stock",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-027",
        "halal_expires_at": "2028-04-30",
        "rating": 4.6,
        "review_count": 1100,
        "sold_count": 15800,
        "discount_pct": 12,
        "image_url": "/images/products/prod_027.jpg",
    },
    "prod_028": {
        "title": "Halal Curry Mee Instant Noodles",
        "description": "Malaysian-style curry noodle soup, MUIS halal certified.",
        "price": 9.8,
        "availability": "out_of_stock",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-028",
        "halal_expires_at": "2028-02-28",
        "rating": 4.9,
        "review_count": 2100,
        "sold_count": 10000,
        "discount_pct": 8,
        "image_url": "/images/products/prod_028.jpg",
    },
    "prod_029": {
        "title": "Family Halal Noodle Bundle 12-pack",
        "description": "Bulk household pack with active MUIS halal certificate.",
        "price": 9.5,
        "availability": "in_stock",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-029",
        "halal_expires_at": "2028-11-30",
        "rating": 4.9,
        "review_count": 1800,
        "sold_count": 22000,
        "discount_pct": 25,
        "image_url": "/images/products/prod_029.jpg",
    },
    "prod_030": {
        "title": "Halal ABC Noodle Soup Sachets 10x",
        "description": "Clear soup noodles. No halal certificate on file.",
        "price": 5.8,
        "availability": "in_stock",
        "halal_status": "unknown",
        "halal_certifier": None,
        "halal_certificate_id": None,
        "halal_expires_at": None,
        "rating": 4.3,
        "review_count": 280,
        "sold_count": 4500,
        "discount_pct": 0,
        "image_url": "/images/products/prod_030.jpg",
    },
    "prod_031": {
        "title": "Beer-Flavored Instant Noodles",
        "description": "Contains alcohol flavoring and pork-derived collagen. Not halal.",
        "price": 7.0,
        "availability": "in_stock",
        "halal_status": "not_certified",
        "halal_certifier": None,
        "halal_certificate_id": None,
        "halal_expires_at": None,
        "rating": 4.7,
        "review_count": 1500,
        "sold_count": 14000,
        "discount_pct": 10,
        "image_url": "/images/products/prod_031.jpg",
    },
    "prod_032": {
        "title": "Classic Halal Noodle Soup Duo",
        "description": "Seller uploaded certificate but it expired in 2024.",
        "price": 6.5,
        "availability": "in_stock",
        "halal_status": "certified",
        "halal_certifier": "MUIS",
        "halal_certificate_id": "HALAL-SG-032-OLD",
        "halal_expires_at": "2024-06-01",
        "rating": 4.8,
        "review_count": 950,
        "sold_count": 7600,
        "discount_pct": 5,
        "image_url": "/images/products/food_groceries.jpg",
    },
}


def main() -> None:
    catalog = json.loads(CATALOG.read_text())
    by_id = {row["product_id"]: row for row in catalog}

    for product_id, patch in NOODLES.items():
        row = by_id[product_id]
        row.update(SG_BASE)
        row.update(patch)
        row["variant_id"] = row["variant_id"]

    CATALOG.write_text(json.dumps(catalog, indent=2) + "\n")
    print(f"Updated {len(NOODLES)} Singapore noodle SKUs in {CATALOG}")


if __name__ == "__main__":
    main()
